[package]
name = "maidan-observability"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true
description = "OpenTelemetry + tracing setup for Maidan."

[dependencies]
opentelemetry = "0.27"
opentelemetry-otlp = { version = "0.27", features = ["grpc-tonic"] }
opentelemetry_sdk = { version = "0.27", features = ["rt-tokio"] }
thiserror.workspace = true
tracing.workspace = true
tracing-opentelemetry = "0.28"
tracing-subscriber = { workspace = true, features = ["env-filter", "json"] }
