#!/usr/bin/env bash
# Regenerate the vendored A2A gRPC code from crates/maidan-server/proto/a2a.proto
# (the official a2aproject/A2A specification/a2a.proto, unmodified).
#
# Writes crates/maidan-server/src/a2a_grpc/generated.rs (prost messages and the
# tonic client/server) and generated.serde.rs (pbjson ProtoJSON impls). Needs
# network access for protoc and the google/api protos; the build itself never
# runs protoc.
#
# Usage:  scripts/gen-a2a-grpc.sh
set -euo pipefail

cd "$(dirname "$0")/.."
root="$PWD"
protoc_version="29.3"
googleapis_commit="master"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

curl -sSfLo "$work/protoc.zip" \
  "https://github.com/protocolbuffers/protobuf/releases/download/v${protoc_version}/protoc-${protoc_version}-linux-x86_64.zip"
unzip -qo "$work/protoc.zip" -d "$work/protoc"
mkdir -p "$work/gapi/google/api"
for f in annotations http client field_behavior launch_stage; do
  curl -sSfLo "$work/gapi/google/api/$f.proto" \
    "https://raw.githubusercontent.com/googleapis/googleapis/${googleapis_commit}/google/api/$f.proto"
done

mkdir -p "$work/gen/src"
cp crates/maidan-server/proto/a2a.proto "$work/gen/a2a.proto"
cp rust-toolchain.toml "$work/gen/"
echo 'fn main() {}' >"$work/gen/src/main.rs"
cat >"$work/gen/Cargo.toml" <<'TOML'
[package]
name = "gen"
version = "0.0.0"
edition = "2021"
[workspace]
[build-dependencies]
tonic-prost-build = "0.14"
prost-build = "0.14"
pbjson-build = "0.9"
TOML
cat >"$work/gen/build.rs" <<RS
fn main() {
    let out = std::path::PathBuf::from("$work/out");
    std::fs::create_dir_all(&out).unwrap();
    let desc = out.join("desc.bin");
    tonic_prost_build::configure()
        .out_dir(&out)
        .file_descriptor_set_path(&desc)
        .compile_well_known_types(true)
        .extern_path(".google.protobuf", "::pbjson_types")
        .compile_protos(&["a2a.proto"], &[".", "$work/protoc/include", "$work/gapi"])
        .unwrap();
    let set = std::fs::read(&desc).unwrap();
    pbjson_build::Builder::new()
        .register_descriptors(&set)
        .unwrap()
        .ignore_unknown_fields()
        .out_dir(&out)
        .build(&[".lf.a2a.v1"])
        .unwrap();
}
RS
(cd "$work/gen" && PROTOC="$work/protoc/bin/protoc" CARGO_TARGET_DIR="$work/target" cargo build --quiet)

dest="$root/crates/maidan-server/src/a2a_grpc"
{
  echo "// Generated by tonic-prost-build 0.14 from proto/a2a.proto (A2A v1.0.1, lf.a2a.v1)."
  echo "// Regenerate with scripts/gen-a2a-grpc.sh; do not edit."
  cat "$work/out/lf.a2a.v1.rs"
  echo
  echo 'include!("generated.serde.rs");'
} >"$dest/generated.rs"
{
  echo "// Generated by pbjson-build 0.9 from proto/a2a.proto. Do not edit."
  cat "$work/out/lf.a2a.v1.serde.rs"
} >"$dest/generated.serde.rs"
rustfmt --edition 2021 "$dest/generated.rs"
echo "regenerated $dest/generated.rs and generated.serde.rs"
