apiVersion: v1
kind: Service
metadata:
  name: maidan-postgres
  namespace: maidan
  labels:
    app.kubernetes.io/name: maidan
    app.kubernetes.io/component: postgres
spec:
  clusterIP: None
  ports:
    - name: pg
      port: 5432
      targetPort: pg
  selector:
    app.kubernetes.io/name: maidan
    app.kubernetes.io/component: postgres
